# Generated by Django 6.0.2 on 2026-02-26 13:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('new', 'Ny'), ('in_progress', 'Pågående'), ('closed', 'Stängd')], default='new', max_length=20)),
                ('internal_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuoteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('company', models.CharField(blank=True, max_length=120)),
                ('service', models.CharField(choices=[('webbdesign', 'Webbdesign'), ('hosting', 'Webbhotell'), ('doman', 'Domän'), ('allt', 'Allt-i-ett')], default='allt', max_length=20)),
                ('budget', models.CharField(choices=[('<5k', '< 5 000 kr'), ('5-15k', '5 000 – 15 000 kr'), ('15-30k', '15 000 – 30 000 kr'), ('30k+', '30 000+ kr'), ('unsure', 'Osäker')], default='unsure', max_length=20)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('new', 'Ny'), ('in_progress', 'Pågående'), ('sent', 'Skickad'), ('won', 'Vunnen'), ('lost', 'Förlorad')], default='new', max_length=20)),
                ('internal_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
